services:
  web:
    container_name: autogen-web-ui
    build: ./config
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    env_file:
      - .env
    volumes:
      - ./data/:/usr/local/autogen-data
    environment:
      - AUTOGENSTUDIO_DATADIR=/usr/local/autogen-data
